spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            # 0：不对路径做任何处理 1：对路径切除一级处理
            - StripPrefix=1

server:
  port: 9527



jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: zzh-secret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  refresh: 300

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/*
      - /swagger/*
      - /*/v2/api-docs
      - /*/*.js
      - /*/*.css
      - /*/*.png
      - /*/*.ico
      - /webjars/springfox-swagger-ui/*
      - /druid/*
      - /actuator/*
      - /*/login
      - /*/register
      - /*/public/*
      - /
      - /login
      - /loginPage