spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            #访问路径：localhost:88/hello?url=baidu 代表跳转到www.baidu.com/hello
            #url带有baidu的自动跳转到https://www.baidu.com
            - Query=url,baidu
server:
  port: 88



jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: zzh-secret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  refresh: 300

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/*
      - /swagger/*
      - /*/v2/api-docs
      - /*/*.js
      - /*/*.css
      - /*/*.png
      - /*/*.ico
      - /webjars/springfox-swagger-ui/*
      - /druid/*
      - /actuator/*
      - /*/login
      - /*/register
      - /*/public/*